common:
  mainName: myapp
  namespace: dev
  label: myapp-label
  appPort: 8000

myappDeploy:
  image:
    name: myapp-container
    repository: vlad584/k8s-monitoring-task-1
    tag: "4.0"
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  livenessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
    initialDelaySeconds: 5
    periodSeconds: 5

myappSecret:
  type: Opaque
  data:
    SECRET_KEY: c2VjcmV0a2V5MTIzNA==

myappHPA:
  minReplicas: 2
  maxReplicas: 3
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 70

myappConfigMap:
  data:
    APP_PORT: "8000"

myappClusterIP:
  ports:
    protocol: TCP
    port: 80
    name: http-metrics