name: Python application

run-name: ${{ github.action }} - ${{ github.ref_name }}

on:
  push:
    branches: ["develop/docker-task-1"]
    paths:
      - 'tasks/docker-task-1/**'
      - '.github/workflows/ci-docker-task-1.yml'

env:
  PythonVersion: 3.10

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Pyhton ${{ env.PythonVersion }} and enable pip cache
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PythonVersion }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics

      - name: Build Docker-image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: .
