apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.mainName }}-clusterip-service
  namespace: {{ .Values.common.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.common.label }}
  ports:
  - protocol: {{ .Values.myappClusterIP.ports.protocol }}
    port: {{ .Values.myappClusterIP.ports.port }}
    targetPort: {{ .Values.common.appPort }}
    name: {{ .Values.myappClusterIP.ports.name }}