apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.common.mainName }}-secret
  namespace: {{ .Values.common.namespace }}
type: {{ .Values.myappSecret.type }}
data:
  SECRET_KEY: {{ .Values.myappSecret.data.SECRET_KEY }}