name: Python application

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  push:
    branches: ["develop/docker-task-1"]
    paths:
      - 'tasks/docker-task-1/**'
      - '.github/workflows/ci-cd-docker-task-1.yml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'tasks/docker-task-1/**'
      - '.github/workflows/ci-cd-docker-task-1.yml'

env:
  PYTHON_VERSION: '3.10'
  DOCKER_IMAGE_NAME: 'docker-task-1'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }} and enable pip cache
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tasks/docker-task-1/requirements.txt
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 tasks/docker-task-1 --show-source --statistics

      - name: Build Docker-image
        uses: docker/build-push-action@v4
        with:
          context: ./tasks/docker-task-1
          file: tasks/docker-task-1/Dockerfile
          push: false

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-artifacts
          path: tasks/docker-task-1

      - name: List artifact contents
        run: ls -R tasks/docker-task-1

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}

    steps:
      - name: Download python artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-artifacts
          path: ./artifacts

      - name: List downloaded artifacts
        run: ls -R ./artifacts

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker-image
        uses: docker/build-push-action@v5
        with:
          context: ./artifacts
          file: artifacts/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
